/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
  By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million (4 000 000), 
  find the sum of the even-valued terms.*/

#include <stdio.h>
using namespace std;

int fibonacci()
{
  int limit = 4000000;
  int fibo_val_a = 1;
  int fibo_val_b = 1;
  int fibo_val_even = fibo_val_a + fibo_val_b;
  int sumOfFiboEven = 0;

  /*
  fibo_val_even = 1+1 = 2 == even!
  sumOfFiboEven = 2+0 = 2
  fibo_val_a = 1+2 = 3
  fibo_val_b = 2+3 = 5
  fibo_val_even = 3+5 = 8 == even
  sumOfFiboEven = 2+8 = 10
  fibo_val_a = 5+8 = 12
  fibo_val_b = 8+12=20
  fibo_val_even = 12+20 = 32
  */
  do
  {
    sumOfFiboEven += fibo_val_even;
    fibo_val_a = fibo_val_b + fibo_val_even;
    fibo_val_b = fibo_val_even + fibo_val_a;
    fibo_val_even = fibo_val_a + fibo_val_b;
  }while(fibo_val_even < limit);

  return sumOfFiboEven;
}

int main()
{

  int even = fibonacci();
  printf("nsumOfEven = %d\n", even );

  //return 0;
}
